services:
  - type: web
    name: kart-api
    env: go
    plan: free
    buildCommand: go test -v -race ./... && go build -o app .
    startCommand: ./app
    envVars:
      - key: PORT
        value: 8080
